document_root: "/www"

hooks:
    build: |
      drush make drupal.make www --prepare-install -y
    enable: |
      drush {{alias}} si standard --db-url=mysql://drupal:drupal@database/drupal --site-name='Drupal 8 Development' --account-name=admin --account-pass=password --account-mail=test@test.com -y
      drush {{alias}} uli
    deploy: |
      drush {{alias}} updb -y
      drush {{}} cr
