document_root: "/www"

hooks:
    build: |
      drush make drupal.make www --prepare-install -y
    enable: |
      drush {{alias}} site-install -y
      drush {{alias}} uli
    deploy: |
      drush {{alias}} updb -y
      drush {{}} cr
