document_root: "/www"

hooks:
    build: |
      git clone --branch 8.0.x http://git.drupal.org/project/drupal.git .
    enable: |
      drush {{alias}} site-install -y
      drush {{alias}} uli
    deploy: |
      drush {{alias}} updb -y
      drush {{}} cr
